// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.EntityFramework.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Entity.Dividend", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<DateTime>("DividendDay");

                    b.Property<bool>("IsDelete");

                    b.Property<DateTime>("RegistrationTime");

                    b.Property<DateTime>("ReleaseTime");

                    b.Property<Guid?>("StockID");

                    b.Property<DateTime>("UpdateDateTime");

                    b.HasKey("ID");

                    b.HasIndex("StockID");

                    b.ToTable("Dividends");
                });

            modelBuilder.Entity("DataAccess.Entity.New", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentUri");

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<bool>("IsDelete");

                    b.Property<DateTime>("ReleaseTime");

                    b.Property<Guid?>("StockID");

                    b.Property<string>("Tite");

                    b.Property<DateTime>("UpdateDateTime");

                    b.HasKey("ID");

                    b.HasIndex("StockID");

                    b.ToTable("News");
                });

            modelBuilder.Entity("DataAccess.Entity.Stock", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("UpdateDateTime");

                    b.HasKey("ID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("DataAccess.Entity.Dividend", b =>
                {
                    b.HasOne("DataAccess.Entity.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockID");
                });

            modelBuilder.Entity("DataAccess.Entity.New", b =>
                {
                    b.HasOne("DataAccess.Entity.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockID");
                });
#pragma warning restore 612, 618
        }
    }
}
